"""Generate a compact low-poly desk lamp as a Wavefront OBJ asset."""

from math import cos, pi, sin
from pathlib import Path


verts: list[tuple[float, float, float]] = []
faces: list[tuple[str, tuple[int, ...]]] = []


def ring(radius: float, z: float, segments: int = 24) -> list[int]:
    indices = []
    for index in range(segments):
        angle = 2 * pi * index / segments
        verts.append((radius * cos(angle), radius * sin(angle), z))
        indices.append(len(verts))
    return indices


def frustum(name: str, bottom_radius: float, top_radius: float, z0: float, z1: float) -> None:
    bottom, top = ring(bottom_radius, z0), ring(top_radius, z1)
    faces.append((name, tuple(reversed(bottom))))
    faces.append((name, tuple(top)))
    for index in range(len(bottom)):
        following = (index + 1) % len(bottom)
        faces.append((name, (bottom[index], bottom[following], top[following], top[index])))


def cylinder_between(name: str, start: tuple[float, float, float], end: tuple[float, float, float], radius: float) -> None:
    # A six-sided tube, oriented around the arm vector.
    dx, dy, dz = (end[i] - start[i] for i in range(3))
    length = (dx * dx + dy * dy + dz * dz) ** 0.5
    axis = (dx / length, dy / length, dz / length)
    helper = (0.0, 0.0, 1.0) if abs(axis[2]) < 0.9 else (0.0, 1.0, 0.0)
    u = (axis[1] * helper[2] - axis[2] * helper[1], axis[2] * helper[0] - axis[0] * helper[2], axis[0] * helper[1] - axis[1] * helper[0])
    magnitude = sum(value * value for value in u) ** 0.5
    u = tuple(value / magnitude for value in u)
    v = (axis[1] * u[2] - axis[2] * u[1], axis[2] * u[0] - axis[0] * u[2], axis[0] * u[1] - axis[1] * u[0])
    first, second = [], []
    for index in range(6):
        angle = 2 * pi * index / 6
        offset = tuple(radius * (cos(angle) * u[i] + sin(angle) * v[i]) for i in range(3))
        verts.append(tuple(start[i] + offset[i] for i in range(3))); first.append(len(verts))
        verts.append(tuple(end[i] + offset[i] for i in range(3))); second.append(len(verts))
    faces.append((name, tuple(reversed(first))))
    faces.append((name, tuple(second)))
    for index in range(6):
        following = (index + 1) % 6
        faces.append((name, (first[index], first[following], second[following], second[index])))


# Base, upright, articulated arm, socket, and a flared shade.
frustum("base", 0.70, 0.56, 0.00, 0.16)
frustum("stem", 0.10, 0.10, 0.16, 0.92)
cylinder_between("arm", (0.0, 0.0, 0.90), (0.52, 0.0, 1.42), 0.075)
cylinder_between("arm", (0.52, 0.0, 1.42), (0.94, 0.0, 1.18), 0.075)
cylinder_between("socket", (0.90, 0.0, 1.16), (1.02, 0.0, 1.09), 0.12)

# Shade is built along the x-axis, opening outward from the socket.
shade_start, shade_end = 1.00, 1.58
for x, radius in ((shade_start, 0.22), (shade_end, 0.44)):
    indices = []
    for index in range(24):
        angle = 2 * pi * index / 24
        verts.append((x, radius * cos(angle), 1.09 + radius * sin(angle)))
        indices.append(len(verts))
    if x == shade_start:
        inner = indices
    else:
        outer = indices
for index in range(24):
    following = (index + 1) % 24
    faces.append(("shade", (inner[index], inner[following], outer[following], outer[index])))

output = Path(__file__).parent / "assets" / "desk_lamp.obj"
with output.open("w", encoding="utf-8") as handle:
    handle.write("# Low-poly desk lamp, generated by create_lamp_obj.py\n")
    for x, y, z in verts:
        handle.write(f"v {x:.6f} {y:.6f} {z:.6f}\n")
    active = None
    for name, face in faces:
        if name != active:
            handle.write(f"o {name}\n")
            active = name
        handle.write("f " + " ".join(map(str, face)) + "\n")
print(output)
